# Generated by Django 2.2 on 2020-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumy_app', '0003_usermodel_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
