# Generated by Django 2.2 on 2020-01-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumy_app', '0007_auto_20200106_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
