# Generated by Django 2.2 on 2020-01-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumy_app', '0008_auto_20200106_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='name',
        ),
    ]
