# Generated by Django 2.2 on 2020-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumy_app', '0012_auto_20200112_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
