# Generated by Django 2.2 on 2020-01-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumy_app', '0013_auto_20200112_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
